language: java
jdk:
    - oraclejdk11

before_install:
     - echo "Deleting old .m2 artifacts..."
     - rm -rf $HOME/.m2/repository/net/wasdev
     - rm -rf $HOME/.m2/repository/io/openliberty
     - echo 'Installing ci.common lib ....'
     - git clone https://github.com/wasdev/ci.common.git ./ci.common
     - cd ./ci.common
     - mvn clean install
     - cd ..
     - git clone https://github.com/dev-tools-for-enterprise-java/boost.git ./boost
     - cd ./boost
     - cd boost-common
     - mvn install -Dinvoker.streamLogs=true
     - cd ../boost-maven
     - mvn install -Dinvoker.streamLogs=true
     - cd ../..

install: true

script: mvn install -DboostRuntime=ol

